version: '3.2'
services:
  database:
    image: mysql:5.7.17
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
  app:
    build: .
    ports:
      - 9292:9292
    depends_on:
      - database
