version: 2
jobs:
  build:
    docker:
       - image: docker:17.06.2-ce-git
         environment:
           COMPOSE_YML: docker-compose.yml
    working_directory: ~/ci-rack
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            -  v1-images-{{ .Branch }}
      - run:
          name: Load Docker images back from cache
          command: |
            set +o pipefail
            docker load -i /cache/app.tar | true
      - run: docker images
      - run:
          name: Install docker-compose
          command: |
            apk add --no-cache py-pip
            pip install docker-compose==1.17.1
      - run:
          name: docker-compose pull
          command: docker-compose -f $COMPOSE_YML pull
      - run:
          name: docker-compose build
          command: |
            docker-compose -f $COMPOSE_YML build \
                           --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                           --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                           app
      - run: docker images
      - run:
          name: Save Docker images
          command: |
            mkdir -p /cache
            docker save -o /cache/app.tar compose_app
      - run: ls -alh /cache/
      - save_cache:
          key: v1-images-{{ .Branch }}-{{ epoch }}
          paths:
            - /cache/app.tar
        
      # Tests
      - run:
          name: Run tests
          command: echo "test"
